"""Partition export_rows and sales_orders by month.

Revision ID: 008_monthly_partition_tables
Revises: 007_export_archival_pipeline
Create Date: 2026-04-09 02:00:00.000000
"""

from datetime import date

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "008_monthly_partition_tables"
down_revision = "007_export_archival_pipeline"
branch_labels = None
depends_on = None


def _add_months(value: date, months: int) -> date:
    month_index = (value.month - 1) + months
    year = value.year + (month_index // 12)
    month = (month_index % 12) + 1
    return date(year, month, 1)


def _create_monthly_partitions(table_name: str, months_back: int = 24, months_forward: int = 12) -> None:
    base = date.today().replace(day=1)
    for offset in range(-months_back, months_forward + 1):
        start = _add_months(base, offset)
        end = _add_months(start, 1)
        partition_name = f"{table_name}_{start.strftime('%Y_%m')}"
        op.execute(
            sa.text(
                f"""
                CREATE TABLE IF NOT EXISTS {partition_name}
                PARTITION OF {table_name}
                FOR VALUES FROM (:start_date) TO (:end_date)
                """
            ).bindparams(start_date=start.isoformat(), end_date=end.isoformat())
        )


def _set_identity_sequence(table_name: str) -> None:
    op.execute(
        sa.text(
            f"""
            SELECT setval(
                pg_get_serial_sequence('{table_name}', 'id'),
                GREATEST((SELECT COALESCE(MAX(id), 0) FROM {table_name}), 1),
                true
            )
            """
        )
    )


def upgrade() -> None:
    # ----- export_rows -----
    op.execute("ALTER TABLE export_rows RENAME TO export_rows_legacy")

    op.execute(
        """
        CREATE TABLE export_rows (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            export_job_id INTEGER NOT NULL REFERENCES export_jobs(id) ON DELETE CASCADE,
            row_number INTEGER NOT NULL,
            entity_type VARCHAR(40) NOT NULL,
            entity_key VARCHAR(180),
            row_hash VARCHAR(64) NOT NULL,
            payload JSONB NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
            partition_month DATE NOT NULL,
            CONSTRAINT uq_export_rows_job_row_number_month
                UNIQUE (export_job_id, row_number, partition_month)
        ) PARTITION BY RANGE (partition_month)
        """
    )
    op.execute("CREATE TABLE IF NOT EXISTS export_rows_default PARTITION OF export_rows DEFAULT")
    _create_monthly_partitions("export_rows")

    op.execute(
        """
        INSERT INTO export_rows (
            id,
            export_job_id,
            row_number,
            entity_type,
            entity_key,
            row_hash,
            payload,
            created_at,
            partition_month
        )
        SELECT
            id,
            export_job_id,
            row_number,
            entity_type,
            entity_key,
            row_hash,
            payload,
            created_at,
            date_trunc('month', created_at)::date
        FROM export_rows_legacy
        """
    )
    _set_identity_sequence("export_rows")
    op.execute("DROP TABLE export_rows_legacy")

    op.create_index("ix_export_rows_export_job_id", "export_rows", ["export_job_id"])
    op.create_index("ix_export_rows_entity_type", "export_rows", ["entity_type"])
    op.create_index("ix_export_rows_entity_key", "export_rows", ["entity_key"])
    op.create_index("ix_export_rows_entity_type_key", "export_rows", ["entity_type", "entity_key"])
    op.create_index("ix_export_rows_partition_month", "export_rows", ["partition_month"])

    # ----- sales_orders -----
    op.execute("ALTER TABLE sales_orders RENAME TO sales_orders_legacy")

    op.execute(
        """
        CREATE TABLE sales_orders (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            order_id VARCHAR(120) NOT NULL,
            sale_order_item_code VARCHAR(120) NOT NULL,
            channel VARCHAR(120),
            sku VARCHAR(120),
            product_name VARCHAR(255),
            qty INTEGER NOT NULL DEFAULT 0,
            selling_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
            status VARCHAR(40) NOT NULL DEFAULT 'created',
            order_date TIMESTAMP WITHOUT TIME ZONE,
            dispatch_date TIMESTAMP WITHOUT TIME ZONE,
            delivery_date TIMESTAMP WITHOUT TIME ZONE,
            cancel_date TIMESTAMP WITHOUT TIME ZONE,
            return_date TIMESTAMP WITHOUT TIME ZONE,
            warehouse VARCHAR(120),
            customer_name VARCHAR(255),
            customer_city VARCHAR(120),
            raw_data JSONB,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
            updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
            partition_month DATE NOT NULL,
            CONSTRAINT uq_sales_orders_order_item_month
                UNIQUE (order_id, sale_order_item_code, partition_month)
        ) PARTITION BY RANGE (partition_month)
        """
    )
    op.execute("CREATE TABLE IF NOT EXISTS sales_orders_default PARTITION OF sales_orders DEFAULT")
    _create_monthly_partitions("sales_orders")

    op.execute(
        """
        INSERT INTO sales_orders (
            id,
            order_id,
            sale_order_item_code,
            channel,
            sku,
            product_name,
            qty,
            selling_price,
            status,
            order_date,
            dispatch_date,
            delivery_date,
            cancel_date,
            return_date,
            warehouse,
            customer_name,
            customer_city,
            raw_data,
            created_at,
            updated_at,
            partition_month
        )
        SELECT
            id,
            order_id,
            sale_order_item_code,
            channel,
            sku,
            product_name,
            qty,
            selling_price,
            status,
            order_date,
            dispatch_date,
            delivery_date,
            cancel_date,
            return_date,
            warehouse,
            customer_name,
            customer_city,
            raw_data,
            created_at,
            updated_at,
            CASE
                WHEN order_date IS NOT NULL THEN date_trunc('month', order_date)::date
                ELSE DATE '2000-01-01'
            END
        FROM sales_orders_legacy
        """
    )
    _set_identity_sequence("sales_orders")
    op.execute("DROP TABLE sales_orders_legacy")

    op.create_index("ix_sales_orders_order_id", "sales_orders", ["order_id"])
    op.create_index("ix_sales_orders_status", "sales_orders", ["status"])
    op.create_index("ix_sales_orders_order_date", "sales_orders", ["order_date"])
    op.create_index("ix_sales_orders_updated_at", "sales_orders", ["updated_at"])
    op.create_index("ix_sales_orders_sku", "sales_orders", ["sku"])
    op.create_index("ix_sales_orders_partition_month", "sales_orders", ["partition_month"])


def downgrade() -> None:
    # ----- sales_orders back to plain table -----
    op.execute("ALTER TABLE sales_orders RENAME TO sales_orders_partitioned")

    op.create_table(
        "sales_orders",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("order_id", sa.String(length=120), nullable=False),
        sa.Column("sale_order_item_code", sa.String(length=120), nullable=False),
        sa.Column("channel", sa.String(length=120), nullable=True),
        sa.Column("sku", sa.String(length=120), nullable=True),
        sa.Column("product_name", sa.String(length=255), nullable=True),
        sa.Column("qty", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("selling_price", sa.Numeric(12, 2), nullable=False, server_default="0"),
        sa.Column("status", sa.String(length=40), nullable=False, server_default="created"),
        sa.Column("order_date", sa.DateTime(), nullable=True),
        sa.Column("dispatch_date", sa.DateTime(), nullable=True),
        sa.Column("delivery_date", sa.DateTime(), nullable=True),
        sa.Column("cancel_date", sa.DateTime(), nullable=True),
        sa.Column("return_date", sa.DateTime(), nullable=True),
        sa.Column("warehouse", sa.String(length=120), nullable=True),
        sa.Column("customer_name", sa.String(length=255), nullable=True),
        sa.Column("customer_city", sa.String(length=120), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=True, server_default=sa.func.now()),
        sa.UniqueConstraint("order_id", "sale_order_item_code", name="uq_sales_orders_order_item"),
    )

    op.execute(
        """
        INSERT INTO sales_orders (
            id,
            order_id,
            sale_order_item_code,
            channel,
            sku,
            product_name,
            qty,
            selling_price,
            status,
            order_date,
            dispatch_date,
            delivery_date,
            cancel_date,
            return_date,
            warehouse,
            customer_name,
            customer_city,
            raw_data,
            created_at,
            updated_at
        )
        SELECT
            id,
            order_id,
            sale_order_item_code,
            channel,
            sku,
            product_name,
            qty,
            selling_price,
            status,
            order_date,
            dispatch_date,
            delivery_date,
            cancel_date,
            return_date,
            warehouse,
            customer_name,
            customer_city,
            raw_data,
            created_at,
            updated_at
        FROM sales_orders_partitioned
        """
    )
    _set_identity_sequence("sales_orders")
    op.execute("DROP TABLE sales_orders_partitioned CASCADE")

    op.create_index("ix_sales_orders_order_id", "sales_orders", ["order_id"])
    op.create_index("ix_sales_orders_status", "sales_orders", ["status"])
    op.create_index("ix_sales_orders_order_date", "sales_orders", ["order_date"])
    op.create_index("ix_sales_orders_updated_at", "sales_orders", ["updated_at"])
    op.create_index("ix_sales_orders_sku", "sales_orders", ["sku"])

    # ----- export_rows back to plain table -----
    op.execute("ALTER TABLE export_rows RENAME TO export_rows_partitioned")

    op.create_table(
        "export_rows",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("export_job_id", sa.Integer(), sa.ForeignKey("export_jobs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_key", sa.String(length=180), nullable=True),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("export_job_id", "row_number", name="uq_export_rows_job_row_number"),
    )

    op.execute(
        """
        INSERT INTO export_rows (
            id,
            export_job_id,
            row_number,
            entity_type,
            entity_key,
            row_hash,
            payload,
            created_at
        )
        SELECT
            id,
            export_job_id,
            row_number,
            entity_type,
            entity_key,
            row_hash,
            payload,
            created_at
        FROM export_rows_partitioned
        """
    )
    _set_identity_sequence("export_rows")
    op.execute("DROP TABLE export_rows_partitioned CASCADE")

    op.create_index("ix_export_rows_export_job_id", "export_rows", ["export_job_id"])
    op.create_index("ix_export_rows_entity_type", "export_rows", ["entity_type"])
    op.create_index("ix_export_rows_entity_key", "export_rows", ["entity_key"])
    op.create_index("ix_export_rows_entity_type_key", "export_rows", ["entity_type", "entity_key"])
