"""Add SyncAuditLog

Revision ID: 4ee7c3339ab0
Revises: 027_add_pp_meta_cols
Create Date: 2026-05-14 12:58:46.617396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ee7c3339ab0'
down_revision = '027_add_pp_meta_cols'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spend_with_tax', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ads_sale', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_sale', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('acos', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('tacos', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('roas', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('roi', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_data_brand'), 'ads_data', ['brand'], unique=False)
    op.create_index(op.f('ix_ads_data_channel'), 'ads_data', ['channel'], unique=False)
    op.create_index(op.f('ix_ads_data_date'), 'ads_data', ['date'], unique=False)
    op.create_index(op.f('ix_ads_data_id'), 'ads_data', ['id'], unique=False)
    op.create_table('fabric_yarn_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yarn', sa.String(length=120), nullable=False),
    sa.Column('yarn_percentage', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('yarn_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fabric_type', sa.String(length=120), nullable=False),
    sa.Column('print', sa.String(length=120), nullable=False),
    sa.Column('fabric_ready_time', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fabric_yarn_master_fabric_type'), 'fabric_yarn_master', ['fabric_type'], unique=False)
    op.create_index(op.f('ix_fabric_yarn_master_id'), 'fabric_yarn_master', ['id'], unique=False)
    op.create_index(op.f('ix_fabric_yarn_master_print'), 'fabric_yarn_master', ['print'], unique=False)
    op.create_index(op.f('ix_fabric_yarn_master_yarn'), 'fabric_yarn_master', ['yarn'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_type', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_code'), 'suppliers', ['supplier_code'], unique=True)
    op.create_table('sync_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=False),
    sa.Column('to_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_expected', sa.Integer(), nullable=True),
    sa.Column('total_synced', sa.Integer(), nullable=True),
    sa.Column('total_failed', sa.Integer(), nullable=True),
    sa.Column('failed_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_status_id'), 'sync_status', ['id'], unique=False)
    op.create_index(op.f('ix_sync_status_period'), 'sync_status', ['period'], unique=True)
    op.create_table('synced_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('created_at_uc', sa.DateTime(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('net_revenue', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('refund', sa.Float(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('include_in_revenue', sa.Boolean(), nullable=True),
    sa.Column('excluded_reason', sa.String(length=200), nullable=True),
    sa.Column('raw_order_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synced_orders_channel'), 'synced_orders', ['channel'], unique=False)
    op.create_index('ix_synced_orders_channel_created', 'synced_orders', ['channel', 'created_at_uc'], unique=False)
    op.create_index(op.f('ix_synced_orders_created_at_uc'), 'synced_orders', ['created_at_uc'], unique=False)
    op.create_index(op.f('ix_synced_orders_id'), 'synced_orders', ['id'], unique=False)
    op.create_index(op.f('ix_synced_orders_order_code'), 'synced_orders', ['order_code'], unique=True)
    op.create_index(op.f('ix_synced_orders_status'), 'synced_orders', ['status'], unique=False)
    op.create_index('ix_synced_orders_status_created', 'synced_orders', ['status', 'created_at_uc'], unique=False)
    op.create_index('ix_synced_orders_synced_at', 'synced_orders', ['synced_at'], unique=False)
    op.create_table('ads_extra_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ads_data_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['ads_data_id'], ['ads_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_extra_metrics_ads_data_id'), 'ads_extra_metrics', ['ads_data_id'], unique=False)
    op.create_index(op.f('ix_ads_extra_metrics_id'), 'ads_extra_metrics', ['id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_product_id'), 'inventory_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_product_type'), 'inventory_transactions', ['product_type'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_transaction_date'), 'inventory_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_transaction_type'), 'inventory_transactions', ['transaction_type'], unique=False)
    op.create_table('knit_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knit_order_number', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('knitter_supplier_id', sa.Integer(), nullable=False),
    sa.Column('fabric_id', sa.Integer(), nullable=False),
    sa.Column('planned_qty_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('gsm', sa.Integer(), nullable=True),
    sa.Column('fabric_type', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabrics.id'], ),
    sa.ForeignKeyConstraint(['knitter_supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knit_orders_id'), 'knit_orders', ['id'], unique=False)
    op.create_index(op.f('ix_knit_orders_knit_order_number'), 'knit_orders', ['knit_order_number'], unique=True)
    op.create_index(op.f('ix_knit_orders_order_date'), 'knit_orders', ['order_date'], unique=False)
    op.create_table('processing_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('processor_supplier_id', sa.Integer(), nullable=False),
    sa.Column('process_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['processor_supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_orders_id'), 'processing_orders', ['id'], unique=False)
    op.create_index(op.f('ix_processing_orders_order_date'), 'processing_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_processing_orders_order_number'), 'processing_orders', ['order_number'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('delivery_terms', sa.String(length=255), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=True),
    sa.Column('extra_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expiry_days', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('freight_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_date'), 'purchase_orders', ['po_date'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('cutting_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cutting_order_number', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('garment_id', sa.Integer(), nullable=False),
    sa.Column('production_plan_id', sa.Integer(), nullable=True),
    sa.Column('fabric_id', sa.Integer(), nullable=False),
    sa.Column('fabric_qty_issued', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('planned_pieces', sa.Integer(), nullable=False),
    sa.Column('size_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('marker_efficiency', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabrics.id'], ),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ),
    sa.ForeignKeyConstraint(['production_plan_id'], ['production_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cutting_orders_cutting_order_number'), 'cutting_orders', ['cutting_order_number'], unique=True)
    op.create_index(op.f('ix_cutting_orders_id'), 'cutting_orders', ['id'], unique=False)
    op.create_index(op.f('ix_cutting_orders_order_date'), 'cutting_orders', ['order_date'], unique=False)
    op.create_table('finished_fabric_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('processing_order_id', sa.Integer(), nullable=False),
    sa.Column('fabric_id', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('qty_rejected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('shade_code', sa.String(length=50), nullable=True),
    sa.Column('gsm_actual', sa.Integer(), nullable=True),
    sa.Column('shrinkage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabrics.id'], ),
    sa.ForeignKeyConstraint(['processing_order_id'], ['processing_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finished_fabric_receipts_id'), 'finished_fabric_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_finished_fabric_receipts_receipt_date'), 'finished_fabric_receipts', ['receipt_date'], unique=False)
    op.create_index(op.f('ix_finished_fabric_receipts_receipt_number'), 'finished_fabric_receipts', ['receipt_number'], unique=True)
    op.create_table('gate_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gate_entry_number', sa.String(length=50), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_time', sa.String(length=10), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('supplier_challan_no', sa.String(length=100), nullable=True),
    sa.Column('supplier_challan_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_entries_entry_date'), 'gate_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_gate_entries_gate_entry_number'), 'gate_entries', ['gate_entry_number'], unique=True)
    op.create_index(op.f('ix_gate_entries_id'), 'gate_entries', ['id'], unique=False)
    op.create_index(op.f('ix_gate_entries_supplier_id'), 'gate_entries', ['supplier_id'], unique=False)
    op.create_table('grey_fabric_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('processing_order_id', sa.Integer(), nullable=False),
    sa.Column('fabric_id', sa.Integer(), nullable=False),
    sa.Column('qty_issued', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabrics.id'], ),
    sa.ForeignKeyConstraint(['processing_order_id'], ['processing_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grey_fabric_issues_id'), 'grey_fabric_issues', ['id'], unique=False)
    op.create_index(op.f('ix_grey_fabric_issues_issue_date'), 'grey_fabric_issues', ['issue_date'], unique=False)
    op.create_index(op.f('ix_grey_fabric_issues_issue_number'), 'grey_fabric_issues', ['issue_number'], unique=True)
    op.create_table('grey_fabric_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('knit_order_id', sa.Integer(), nullable=False),
    sa.Column('fabric_id', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('qty_rejected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('gsm_actual', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabrics.id'], ),
    sa.ForeignKeyConstraint(['knit_order_id'], ['knit_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grey_fabric_receipts_id'), 'grey_fabric_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_grey_fabric_receipts_knit_order_id'), 'grey_fabric_receipts', ['knit_order_id'], unique=False)
    op.create_index(op.f('ix_grey_fabric_receipts_receipt_date'), 'grey_fabric_receipts', ['receipt_date'], unique=False)
    op.create_index(op.f('ix_grey_fabric_receipts_receipt_number'), 'grey_fabric_receipts', ['receipt_number'], unique=True)
    op.create_table('po_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('yarn_id', sa.Integer(), nullable=True),
    sa.Column('fabric_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('order_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('net_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pending_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabrics.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['yarn_id'], ['yarns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_items_id'), 'po_items', ['id'], unique=False)
    op.create_index(op.f('ix_po_items_po_id'), 'po_items', ['po_id'], unique=False)
    op.create_table('yarn_issues_to_knitter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('knit_order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['knit_order_id'], ['knit_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yarn_issues_to_knitter_id'), 'yarn_issues_to_knitter', ['id'], unique=False)
    op.create_index(op.f('ix_yarn_issues_to_knitter_issue_date'), 'yarn_issues_to_knitter', ['issue_date'], unique=False)
    op.create_index(op.f('ix_yarn_issues_to_knitter_issue_number'), 'yarn_issues_to_knitter', ['issue_number'], unique=True)
    op.create_index(op.f('ix_yarn_issues_to_knitter_knit_order_id'), 'yarn_issues_to_knitter', ['knit_order_id'], unique=False)
    op.create_table('cutting_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cutting_order_id', sa.Integer(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('pieces_cut', sa.Integer(), nullable=False),
    sa.Column('pieces_ok', sa.Integer(), nullable=False),
    sa.Column('pieces_rejected', sa.Integer(), nullable=True),
    sa.Column('fabric_used_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fabric_wastage_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('size_breakdown_actual', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_by', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cutting_order_id'], ['cutting_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cutting_checks_id'), 'cutting_checks', ['id'], unique=False)
    op.create_table('mrns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mrn_number', sa.String(length=50), nullable=False),
    sa.Column('mrn_date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('gate_entry_id', sa.Integer(), nullable=True),
    sa.Column('supplier_doc_no', sa.String(length=100), nullable=True),
    sa.Column('supplier_doc_date', sa.Date(), nullable=True),
    sa.Column('mrn_type', sa.String(length=30), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_type', sa.String(length=10), nullable=True),
    sa.Column('excise_duty_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('excise_duty_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('freight_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_charges', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gate_entry_id'], ['gate_entries.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mrns_id'), 'mrns', ['id'], unique=False)
    op.create_index(op.f('ix_mrns_mrn_date'), 'mrns', ['mrn_date'], unique=False)
    op.create_index(op.f('ix_mrns_mrn_number'), 'mrns', ['mrn_number'], unique=True)
    op.create_index(op.f('ix_mrns_supplier_id'), 'mrns', ['supplier_id'], unique=False)
    op.create_table('stitching_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stitching_order_number', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('cutting_order_id', sa.Integer(), nullable=False),
    sa.Column('stitcher_supplier_id', sa.Integer(), nullable=True),
    sa.Column('pieces_issued', sa.Integer(), nullable=False),
    sa.Column('size_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('stitching_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cutting_order_id'], ['cutting_orders.id'], ),
    sa.ForeignKeyConstraint(['stitcher_supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stitching_orders_id'), 'stitching_orders', ['id'], unique=False)
    op.create_index(op.f('ix_stitching_orders_order_date'), 'stitching_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_stitching_orders_stitching_order_number'), 'stitching_orders', ['stitching_order_number'], unique=True)
    op.create_table('yarn_issue_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('yarn_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('returned_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['yarn_issues_to_knitter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['yarn_id'], ['yarns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yarn_issue_items_id'), 'yarn_issue_items', ['id'], unique=False)
    op.create_table('garment_finishing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stitching_order_id', sa.Integer(), nullable=False),
    sa.Column('garment_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('stage_date', sa.Date(), nullable=False),
    sa.Column('pieces_in', sa.Integer(), nullable=False),
    sa.Column('pieces_ok', sa.Integer(), nullable=False),
    sa.Column('pieces_rejected', sa.Integer(), nullable=True),
    sa.Column('size_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ),
    sa.ForeignKeyConstraint(['stitching_order_id'], ['stitching_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garment_finishing_id'), 'garment_finishing', ['id'], unique=False)
    op.create_index(op.f('ix_garment_finishing_stage_date'), 'garment_finishing', ['stage_date'], unique=False)
    op.create_table('mrn_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mrn_id', sa.Integer(), nullable=False),
    sa.Column('po_item_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('yarn_id', sa.Integer(), nullable=True),
    sa.Column('fabric_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('bags', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('disc_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('p_type', sa.String(length=30), nullable=True),
    sa.Column('geno', sa.String(length=50), nullable=True),
    sa.Column('gpo', sa.String(length=50), nullable=True),
    sa.Column('kpo', sa.String(length=50), nullable=True),
    sa.Column('pono', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('mill', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabrics.id'], ),
    sa.ForeignKeyConstraint(['mrn_id'], ['mrns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_item_id'], ['po_items.id'], ),
    sa.ForeignKeyConstraint(['yarn_id'], ['yarns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mrn_items_id'), 'mrn_items', ['id'], unique=False)
    op.create_index(op.f('ix_mrn_items_mrn_id'), 'mrn_items', ['mrn_id'], unique=False)
    op.create_table('barcode_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garment_finishing_id', sa.Integer(), nullable=False),
    sa.Column('garment_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('printed_at', sa.DateTime(), nullable=True),
    sa.Column('is_printed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garment_finishing_id'], ['garment_finishing.id'], ),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barcode_labels_barcode'), 'barcode_labels', ['barcode'], unique=True)
    op.create_index(op.f('ix_barcode_labels_id'), 'barcode_labels', ['id'], unique=False)
    op.drop_index('ix_order_sync_jobs_created', table_name='order_sync_jobs')
    op.drop_index('ix_order_sync_jobs_status', table_name='order_sync_jobs')
    op.drop_table('order_sync_jobs')
    op.drop_index('ix_unicommerce_orders_channel', table_name='unicommerce_orders')
    op.drop_index('ix_unicommerce_orders_channel_date', table_name='unicommerce_orders')
    op.drop_index('ix_unicommerce_orders_date_status', table_name='unicommerce_orders')
    op.drop_index('ix_unicommerce_orders_display_order_date', table_name='unicommerce_orders')
    op.drop_index('ix_unicommerce_orders_order_code', table_name='unicommerce_orders')
    op.drop_index('ix_unicommerce_orders_order_created_at', table_name='unicommerce_orders')
    op.drop_index('ix_unicommerce_orders_status', table_name='unicommerce_orders')
    op.drop_table('unicommerce_orders')
    op.drop_table('sync_checkpoints')
    op.drop_index('ix_webhook_events_order', table_name='webhook_events')
    op.drop_index('ix_webhook_events_received', table_name='webhook_events')
    op.drop_index('ix_webhook_events_type', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('ix_data_verification_domain_period', table_name='data_verification_status')
    op.drop_index('ix_data_verification_status_data_domain', table_name='data_verification_status')
    op.drop_index('ix_data_verification_status_period_type', table_name='data_verification_status')
    op.drop_index('ix_data_verification_status_status', table_name='data_verification_status')
    op.drop_index('ix_data_verification_status_verified_at', table_name='data_verification_status')
    op.drop_table('data_verification_status')
    op.drop_table('cache_metadata')
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_discounts_id'), 'discounts', ['id'], unique=False)
    op.create_index(op.f('ix_export_jobs_id'), 'export_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_export_jobs_requested_from'), 'export_jobs', ['requested_from'], unique=False)
    op.create_index(op.f('ix_export_jobs_requested_to'), 'export_jobs', ['requested_to'], unique=False)
    op.drop_index('uq_export_rows_job_row_number_month', table_name='export_rows')
    op.create_unique_constraint('uq_export_rows_job_row_number_month', 'export_rows', ['export_job_id', 'row_number', 'partition_month'])
    op.create_index(op.f('ix_export_rows_id'), 'export_rows', ['id'], unique=False)
    op.create_foreign_key(None, 'export_rows', 'export_jobs', ['export_job_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_fabrics_id'), 'fabrics', ['id'], unique=False)
    op.drop_constraint('garments_style_sku_key', 'garments', type_='unique')
    op.drop_index('ix_garments_business_unit', table_name='garments')
    op.drop_index('ix_garments_style_sku', table_name='garments')
    op.create_index(op.f('ix_garments_style_sku'), 'garments', ['style_sku'], unique=True)
    op.create_index(op.f('ix_garments_id'), 'garments', ['id'], unique=False)
    op.drop_column('garments', 'business_unit')
    op.drop_constraint('uix_garment_size', 'inventory', type_='unique')
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.alter_column('inventory_snapshots', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('idx_inventory_snapshots_extra_fields_gin', table_name='inventory_snapshots', postgresql_using='gin')
    op.create_index(op.f('ix_inventory_snapshots_id'), 'inventory_snapshots', ['id'], unique=False)
    op.drop_column('inventory_snapshots', 'extra_fields')
    op.create_index(op.f('ix_login_history_id'), 'login_history', ['id'], unique=False)
    op.create_index(op.f('ix_paid_ads_id'), 'paid_ads', ['id'], unique=False)
    op.create_index(op.f('ix_panels_id'), 'panels', ['id'], unique=False)
    op.create_index(op.f('ix_processes_id'), 'processes', ['id'], unique=False)
    op.drop_index('ix_product_master_collection', table_name='product_master')
    op.drop_index('ix_product_master_season', table_name='product_master')
    op.drop_index('ix_product_master_type', table_name='product_master')
    op.drop_constraint('product_master_sku_key', 'product_master', type_='unique')
    op.create_index(op.f('ix_production_activities_id'), 'production_activities', ['id'], unique=False)
    op.create_index(op.f('ix_production_planning_history_id'), 'production_planning_history', ['id'], unique=False)
    op.create_index(op.f('ix_production_planning_reports_id'), 'production_planning_reports', ['id'], unique=False)
    op.create_index(op.f('ix_production_plans_id'), 'production_plans', ['id'], unique=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.drop_index('idx_sales_orders_extra_fields_gin', table_name='sales_orders', postgresql_using='gin')
    op.create_index(op.f('ix_sales_orders_channel'), 'sales_orders', ['channel'], unique=False)
    op.create_index(op.f('ix_sales_orders_id'), 'sales_orders', ['id'], unique=False)
    op.drop_index('uq_sales_returns_return_code', table_name='sales_returns')
    op.drop_index('ix_sales_returns_return_code', table_name='sales_returns')
    op.create_index(op.f('ix_sales_returns_return_code'), 'sales_returns', ['return_code'], unique=True)
    op.create_index(op.f('ix_sales_returns_id'), 'sales_returns', ['id'], unique=False)
    op.drop_constraint('uq_shopify_master_data_variant_sku', 'shopify_master_data', type_='unique')
    op.drop_index('ix_shopify_master_data_variant_sku', table_name='shopify_master_data')
    op.create_index(op.f('ix_shopify_master_data_variant_sku'), 'shopify_master_data', ['variant_sku'], unique=True)
    op.create_index(op.f('ix_shopify_master_data_id'), 'shopify_master_data', ['id'], unique=False)
    op.drop_index('ix_sync_logs_started_at', table_name='sync_logs')
    op.create_index(op.f('ix_sync_logs_id'), 'sync_logs', ['id'], unique=False)
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('uq_users_single_developer', table_name='users', postgresql_where="(lower((role)::text) = 'developer'::text)")
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_yarns_id'), 'yarns', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yarns_id'), table_name='yarns')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('uq_users_single_developer', 'users', ['role'], unique=True, postgresql_where="(lower((role)::text) = 'developer'::text)")
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('user_sessions', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('user_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_sync_logs_id'), table_name='sync_logs')
    op.create_index('ix_sync_logs_started_at', 'sync_logs', ['started_at'], unique=False)
    op.drop_index(op.f('ix_shopify_master_data_id'), table_name='shopify_master_data')
    op.drop_index(op.f('ix_shopify_master_data_variant_sku'), table_name='shopify_master_data')
    op.create_index('ix_shopify_master_data_variant_sku', 'shopify_master_data', ['variant_sku'], unique=False)
    op.create_unique_constraint('uq_shopify_master_data_variant_sku', 'shopify_master_data', ['variant_sku'])
    op.drop_index(op.f('ix_sales_returns_id'), table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_return_code'), table_name='sales_returns')
    op.create_index('ix_sales_returns_return_code', 'sales_returns', ['return_code'], unique=False)
    op.create_index('uq_sales_returns_return_code', 'sales_returns', ['return_code'], unique=True)
    op.drop_index(op.f('ix_sales_orders_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_channel'), table_name='sales_orders')
    op.create_index('idx_sales_orders_extra_fields_gin', 'sales_orders', ['extra_fields'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_index(op.f('ix_production_plans_id'), table_name='production_plans')
    op.drop_index(op.f('ix_production_planning_reports_id'), table_name='production_planning_reports')
    op.drop_index(op.f('ix_production_planning_history_id'), table_name='production_planning_history')
    op.drop_index(op.f('ix_production_activities_id'), table_name='production_activities')
    op.create_unique_constraint('product_master_sku_key', 'product_master', ['sku'])
    op.create_index('ix_product_master_type', 'product_master', ['type'], unique=False)
    op.create_index('ix_product_master_season', 'product_master', ['season'], unique=False)
    op.create_index('ix_product_master_collection', 'product_master', ['collection'], unique=False)
    op.drop_index(op.f('ix_processes_id'), table_name='processes')
    op.drop_index(op.f('ix_panels_id'), table_name='panels')
    op.drop_index(op.f('ix_paid_ads_id'), table_name='paid_ads')
    op.drop_index(op.f('ix_login_history_id'), table_name='login_history')
    op.add_column('inventory_snapshots', sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_inventory_snapshots_id'), table_name='inventory_snapshots')
    op.create_index('idx_inventory_snapshots_extra_fields_gin', 'inventory_snapshots', ['extra_fields'], unique=False, postgresql_using='gin')
    op.alter_column('inventory_snapshots', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.create_unique_constraint('uix_garment_size', 'inventory', ['garment_id', 'size'])
    op.add_column('garments', sa.Column('business_unit', sa.VARCHAR(length=20), server_default=sa.text("'GARMENTS'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_garments_id'), table_name='garments')
    op.drop_index(op.f('ix_garments_style_sku'), table_name='garments')
    op.create_index('ix_garments_style_sku', 'garments', ['style_sku'], unique=False)
    op.create_index('ix_garments_business_unit', 'garments', ['business_unit'], unique=False)
    op.create_unique_constraint('garments_style_sku_key', 'garments', ['style_sku'])
    op.drop_index(op.f('ix_fabrics_id'), table_name='fabrics')
    op.drop_constraint(None, 'export_rows', type_='foreignkey')
    op.drop_index(op.f('ix_export_rows_id'), table_name='export_rows')
    op.drop_constraint('uq_export_rows_job_row_number_month', 'export_rows', type_='unique')
    op.create_index('uq_export_rows_job_row_number_month', 'export_rows', ['export_job_id', 'row_number', 'partition_month'], unique=True)
    op.drop_index(op.f('ix_export_jobs_requested_to'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_requested_from'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_discounts_id'), table_name='discounts')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.create_table('cache_metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_computed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('data_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('computation_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cache_metadata_pkey'),
    sa.UniqueConstraint('cache_key', name='cache_metadata_cache_key_key')
    )
    op.create_table('data_verification_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_domain', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('period_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mismatch_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('source_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('target_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('source_total', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('target_total', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='data_verification_status_pkey'),
    sa.UniqueConstraint('data_domain', 'period_type', 'period_start', 'period_end', name='uq_data_verification_period')
    )
    op.create_index('ix_data_verification_status_verified_at', 'data_verification_status', ['verified_at'], unique=False)
    op.create_index('ix_data_verification_status_status', 'data_verification_status', ['status'], unique=False)
    op.create_index('ix_data_verification_status_period_type', 'data_verification_status', ['period_type'], unique=False)
    op.create_index('ix_data_verification_status_data_domain', 'data_verification_status', ['data_domain'], unique=False)
    op.create_index('ix_data_verification_domain_period', 'data_verification_status', ['data_domain', 'period_start', 'period_end'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('order_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='webhook_events_pkey'),
    sa.UniqueConstraint('event_id', name='webhook_events_event_id_key')
    )
    op.create_index('ix_webhook_events_type', 'webhook_events', ['event_type'], unique=False)
    op.create_index('ix_webhook_events_received', 'webhook_events', ['received_at'], unique=False)
    op.create_index('ix_webhook_events_order', 'webhook_events', ['order_code'], unique=False)
    op.create_table('sync_checkpoints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sync_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_sync_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_order_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_order_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('orders_synced', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sync_checkpoints_pkey'),
    sa.UniqueConstraint('sync_type', name='sync_checkpoints_sync_type_key')
    )
    op.create_table('unicommerce_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('display_order_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('unicommerce_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_order_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('order_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('gross_sales', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('net_sales', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_discount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('tax_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('shipping_charges', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('items_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('webhook_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='unicommerce_orders_pkey')
    )
    op.create_index('ix_unicommerce_orders_status', 'unicommerce_orders', ['status'], unique=False)
    op.create_index('ix_unicommerce_orders_order_created_at', 'unicommerce_orders', ['order_created_at'], unique=False)
    op.create_index('ix_unicommerce_orders_order_code', 'unicommerce_orders', ['order_code'], unique=True)
    op.create_index('ix_unicommerce_orders_display_order_date', 'unicommerce_orders', ['display_order_date'], unique=False)
    op.create_index('ix_unicommerce_orders_date_status', 'unicommerce_orders', ['order_created_at', 'status', 'is_deleted'], unique=False)
    op.create_index('ix_unicommerce_orders_channel_date', 'unicommerce_orders', ['channel', 'order_created_at'], unique=False)
    op.create_index('ix_unicommerce_orders_channel', 'unicommerce_orders', ['channel'], unique=False)
    op.create_table('order_sync_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('sync_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('total_orders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processed_orders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_orders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('to_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='order_sync_jobs_pkey'),
    sa.UniqueConstraint('job_id', name='order_sync_jobs_job_id_key')
    )
    op.create_index('ix_order_sync_jobs_status', 'order_sync_jobs', ['status'], unique=False)
    op.create_index('ix_order_sync_jobs_created', 'order_sync_jobs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_barcode_labels_id'), table_name='barcode_labels')
    op.drop_index(op.f('ix_barcode_labels_barcode'), table_name='barcode_labels')
    op.drop_table('barcode_labels')
    op.drop_index(op.f('ix_mrn_items_mrn_id'), table_name='mrn_items')
    op.drop_index(op.f('ix_mrn_items_id'), table_name='mrn_items')
    op.drop_table('mrn_items')
    op.drop_index(op.f('ix_garment_finishing_stage_date'), table_name='garment_finishing')
    op.drop_index(op.f('ix_garment_finishing_id'), table_name='garment_finishing')
    op.drop_table('garment_finishing')
    op.drop_index(op.f('ix_yarn_issue_items_id'), table_name='yarn_issue_items')
    op.drop_table('yarn_issue_items')
    op.drop_index(op.f('ix_stitching_orders_stitching_order_number'), table_name='stitching_orders')
    op.drop_index(op.f('ix_stitching_orders_order_date'), table_name='stitching_orders')
    op.drop_index(op.f('ix_stitching_orders_id'), table_name='stitching_orders')
    op.drop_table('stitching_orders')
    op.drop_index(op.f('ix_mrns_supplier_id'), table_name='mrns')
    op.drop_index(op.f('ix_mrns_mrn_number'), table_name='mrns')
    op.drop_index(op.f('ix_mrns_mrn_date'), table_name='mrns')
    op.drop_index(op.f('ix_mrns_id'), table_name='mrns')
    op.drop_table('mrns')
    op.drop_index(op.f('ix_cutting_checks_id'), table_name='cutting_checks')
    op.drop_table('cutting_checks')
    op.drop_index(op.f('ix_yarn_issues_to_knitter_knit_order_id'), table_name='yarn_issues_to_knitter')
    op.drop_index(op.f('ix_yarn_issues_to_knitter_issue_number'), table_name='yarn_issues_to_knitter')
    op.drop_index(op.f('ix_yarn_issues_to_knitter_issue_date'), table_name='yarn_issues_to_knitter')
    op.drop_index(op.f('ix_yarn_issues_to_knitter_id'), table_name='yarn_issues_to_knitter')
    op.drop_table('yarn_issues_to_knitter')
    op.drop_index(op.f('ix_po_items_po_id'), table_name='po_items')
    op.drop_index(op.f('ix_po_items_id'), table_name='po_items')
    op.drop_table('po_items')
    op.drop_index(op.f('ix_grey_fabric_receipts_receipt_number'), table_name='grey_fabric_receipts')
    op.drop_index(op.f('ix_grey_fabric_receipts_receipt_date'), table_name='grey_fabric_receipts')
    op.drop_index(op.f('ix_grey_fabric_receipts_knit_order_id'), table_name='grey_fabric_receipts')
    op.drop_index(op.f('ix_grey_fabric_receipts_id'), table_name='grey_fabric_receipts')
    op.drop_table('grey_fabric_receipts')
    op.drop_index(op.f('ix_grey_fabric_issues_issue_number'), table_name='grey_fabric_issues')
    op.drop_index(op.f('ix_grey_fabric_issues_issue_date'), table_name='grey_fabric_issues')
    op.drop_index(op.f('ix_grey_fabric_issues_id'), table_name='grey_fabric_issues')
    op.drop_table('grey_fabric_issues')
    op.drop_index(op.f('ix_gate_entries_supplier_id'), table_name='gate_entries')
    op.drop_index(op.f('ix_gate_entries_id'), table_name='gate_entries')
    op.drop_index(op.f('ix_gate_entries_gate_entry_number'), table_name='gate_entries')
    op.drop_index(op.f('ix_gate_entries_entry_date'), table_name='gate_entries')
    op.drop_table('gate_entries')
    op.drop_index(op.f('ix_finished_fabric_receipts_receipt_number'), table_name='finished_fabric_receipts')
    op.drop_index(op.f('ix_finished_fabric_receipts_receipt_date'), table_name='finished_fabric_receipts')
    op.drop_index(op.f('ix_finished_fabric_receipts_id'), table_name='finished_fabric_receipts')
    op.drop_table('finished_fabric_receipts')
    op.drop_index(op.f('ix_cutting_orders_order_date'), table_name='cutting_orders')
    op.drop_index(op.f('ix_cutting_orders_id'), table_name='cutting_orders')
    op.drop_index(op.f('ix_cutting_orders_cutting_order_number'), table_name='cutting_orders')
    op.drop_table('cutting_orders')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_date'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_processing_orders_order_number'), table_name='processing_orders')
    op.drop_index(op.f('ix_processing_orders_order_date'), table_name='processing_orders')
    op.drop_index(op.f('ix_processing_orders_id'), table_name='processing_orders')
    op.drop_table('processing_orders')
    op.drop_index(op.f('ix_knit_orders_order_date'), table_name='knit_orders')
    op.drop_index(op.f('ix_knit_orders_knit_order_number'), table_name='knit_orders')
    op.drop_index(op.f('ix_knit_orders_id'), table_name='knit_orders')
    op.drop_table('knit_orders')
    op.drop_index(op.f('ix_inventory_transactions_transaction_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_transaction_date'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_product_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_product_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_ads_extra_metrics_id'), table_name='ads_extra_metrics')
    op.drop_index(op.f('ix_ads_extra_metrics_ads_data_id'), table_name='ads_extra_metrics')
    op.drop_table('ads_extra_metrics')
    op.drop_index('ix_synced_orders_synced_at', table_name='synced_orders')
    op.drop_index('ix_synced_orders_status_created', table_name='synced_orders')
    op.drop_index(op.f('ix_synced_orders_status'), table_name='synced_orders')
    op.drop_index(op.f('ix_synced_orders_order_code'), table_name='synced_orders')
    op.drop_index(op.f('ix_synced_orders_id'), table_name='synced_orders')
    op.drop_index(op.f('ix_synced_orders_created_at_uc'), table_name='synced_orders')
    op.drop_index('ix_synced_orders_channel_created', table_name='synced_orders')
    op.drop_index(op.f('ix_synced_orders_channel'), table_name='synced_orders')
    op.drop_table('synced_orders')
    op.drop_index(op.f('ix_sync_status_period'), table_name='sync_status')
    op.drop_index(op.f('ix_sync_status_id'), table_name='sync_status')
    op.drop_table('sync_status')
    op.drop_index(op.f('ix_suppliers_supplier_code'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_fabric_yarn_master_yarn'), table_name='fabric_yarn_master')
    op.drop_index(op.f('ix_fabric_yarn_master_print'), table_name='fabric_yarn_master')
    op.drop_index(op.f('ix_fabric_yarn_master_id'), table_name='fabric_yarn_master')
    op.drop_index(op.f('ix_fabric_yarn_master_fabric_type'), table_name='fabric_yarn_master')
    op.drop_table('fabric_yarn_master')
    op.drop_index(op.f('ix_ads_data_id'), table_name='ads_data')
    op.drop_index(op.f('ix_ads_data_date'), table_name='ads_data')
    op.drop_index(op.f('ix_ads_data_channel'), table_name='ads_data')
    op.drop_index(op.f('ix_ads_data_brand'), table_name='ads_data')
    op.drop_table('ads_data')
    # ### end Alembic commands ###
