"""extract_catalog_fields

Revision ID: e636796d27cc
Revises: be04a72e486f
Create Date: 2026-05-30 15:08:03.620715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e636796d27cc'
down_revision = 'be04a72e486f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facility_inventory_snapshot', sa.Column('color', sa.String(length=120), nullable=True))
    op.add_column('facility_inventory_snapshot', sa.Column('size', sa.String(length=120), nullable=True))
    op.add_column('facility_inventory_snapshot', sa.Column('brand', sa.String(length=120), nullable=True))
    op.add_column('facility_inventory_snapshot', sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=True))
    op.alter_column('facility_inventory_snapshot', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.create_index(op.f('ix_facility_inventory_snapshot_brand'), 'facility_inventory_snapshot', ['brand'], unique=False)
    op.create_index(op.f('ix_facility_inventory_snapshot_category'), 'facility_inventory_snapshot', ['category'], unique=False)
    op.create_index(op.f('ix_facility_inventory_snapshot_color'), 'facility_inventory_snapshot', ['color'], unique=False)
    op.create_index(op.f('ix_facility_inventory_snapshot_size'), 'facility_inventory_snapshot', ['size'], unique=False)
    op.drop_index('uq_users_single_developer', table_name='users', postgresql_where="(lower((role)::text) = 'developer'::text)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_users_single_developer', 'users', ['role'], unique=True, postgresql_where="(lower((role)::text) = 'developer'::text)")
    op.drop_index(op.f('ix_facility_inventory_snapshot_size'), table_name='facility_inventory_snapshot')
    op.drop_index(op.f('ix_facility_inventory_snapshot_color'), table_name='facility_inventory_snapshot')
    op.drop_index(op.f('ix_facility_inventory_snapshot_category'), table_name='facility_inventory_snapshot')
    op.drop_index(op.f('ix_facility_inventory_snapshot_brand'), table_name='facility_inventory_snapshot')
    op.alter_column('facility_inventory_snapshot', 'category',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('facility_inventory_snapshot', 'mrp')
    op.drop_column('facility_inventory_snapshot', 'brand')
    op.drop_column('facility_inventory_snapshot', 'size')
    op.drop_column('facility_inventory_snapshot', 'color')
    # ### end Alembic commands ###
